### ISSUE TITLE
Unable to build for el6

### ISSUE THREAD

**Issue by nheetesonne** [varnishcache/pkg-varnish-cache#126]
I'm trying to build the varnish 6.0.3 RPM for use on RHEL6 systems.
I've set the environment variables REL and ARCH to the following:
`export REL=el6
  export ARCH=x86_64`

Next step is to build the rpm with 

`./package-rpm`

This sets up the mock environment correctly but fails when actually building the RPM:

```
ERROR: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/varnish.spec
```

I also see this only builds a source RPM?
Can I still build for RHEL6?

**Comment by Dridi** [comment]
Actually, you would rather `export ELVER=el6` to your environment but we dropped support for el6 when 6.0 was released because it will reach its end of life before Varnish 6.

Our packaging as a result only targets systemd systems in our pool of supported platforms but the old sysv scripts are still present in the repository.

Unfortunately, it's up to you to edit the RPM spec and the `package-rpm` script to do that because we don't support this use case.
