### ISSUE TITLE
Support Ubuntu 16.04 Xenial LTS

### ISSUE THREAD

**Issue by geerlingguy** [varnishcache/pkg-varnish-cache#23]
Currently, when attempting to install Varnish on Ubuntu 16.04 LTS, I get:

```
The repository 'http://repo.varnish-cache.org/ubuntu xenial Release' does not have a Release file.
Failed to fetch http://repo.varnish-cache.org/ubuntu/dists/xenial/varnish-4.0/binary-amd64/Packages  404  Not Found [IP: 194.31.39.155 80]
Failed to fetch http://repo.varnish-cache.org/ubuntu/dists/xenial/varnish-4.0/binary-i386/Packages  404  Not Found [IP: 194.31.39.155 80]
```

Is a Xenial release channel in the works? I know it's only been a day... :)

**Comment by lkarsten** [comment]
Which version of varnish is included in Xenial?

I don't see us building packages of 4.0 for it. I think the consideration is if we will do 4.1 packages for xenial or leave that to the distribution.

**Comment by geerlingguy** [comment]
It looks like 4.1.1 is included: http://packages.ubuntu.com/xenial/web/varnish

If that's the case, do you think 4.0/4.1 would ever be supported by Varnish's own PPA, or should I switch my Ansible playbook to use the system packages if on Ubuntu 16.04?

**Comment by lkarsten** [comment]
Hi.

Thanks for looking it up. At least it is 4.1, so that should be good enough.

It is still an open question if we'll add xenial packages. We're moving to a rolling 6 month release cycle starting from September, and we haven't decided how "stable" versions should be handled. Packaging takes effort away from writing code, so we prefer to avoid it if the distros can fill the gap.

Unless the trusty packages work for you, I recommend you go with the xenial default one for now.

If we can get packages that work on all recent ubuntus and debians, that would make the decision to keep builing packages easier. I haven't had time to look at this yet.

Closing this as we don't have immediate plans to do it and keeping it open just makes the buglist longer.

I'll update the web page when we have decided what to do in this space.
