### ISSUE TITLE
Reload script needs some love.

### ISSUE THREAD

**Issue by lkarsten** [varnishcache/pkg-varnish-cache#30]
> [14:43:55] < ssm> scn: the reload script in the debian package in Debian does not work well anymore, probably better to drop the systemd "reload" action, and let people use varnishadm explicitly, unless someone has a script that works. 
> [14:44:57] < scn> ssm: i think having reload in place has value. shall we clean up the script?
> [14:45:39] < ssm> probably.

**Comment by Dridi** [comment]
That could be a good occasion to drop the two reload scripts in favor of a single one.

**Comment by infintesimal** [comment]
Hi all, I have some fixes for reload-vcl that I will set to pull request soon (later today I hope). I thought I'd run some architectural stuff past anyone who cares.

My current config I use the service varnish stop|start|restart constructs and uses the chrooting -j option and so have customized
/etc/init.d/varnish
/etc/default/varnish
/usr/share/varnish/reload-vcl

The comment notes in the current distro's /etc/default/varnish file are somewhat incorrect in that they assert if one has systemd installed that /usr/default/varnish file is obsoleted. This is not true, as my ocnfig works fine and I have systemd installed. I just don't expose the varnish control commands to systemd.

So, with all this context:
1) Should we take any position on systemctl/systemd versus the service varnish start|stop|start control of the app (BSD/Debian vs.  SysV variants???)
2) Is it a more general mistake to think of varnish as a system level service? My instincts here tell me it's more of a per app kind of thing; assuming infinite memory, I could install a varnish for every webapp/webservice I have running on a server. So maybe we should leave the entire system level bits alone or lower priority and just provide wrapper scripts for an unprivileged user to spin up their own varnish instance (stealing from apache, say, varnish_ctl start|stop|restart (I am vaguely aware there might be some user constraints around creating shared memory segments, but I have to refresh my memory here as it pertains to varnish).
3) reload-vcl is its own can of worms. I think we should separate the construct of reload-vcl and restart varnish.  The latter will force the former but does the former really need the latter (I don't think so).

Short term, I will set up the pull request for the 4.1.3 packaging to allow for this stuff to work in at least Ubuntu in a context of using service varnish start/stop/restart and won't pay too much attention to the systemctl variation.  The reason that I am not yet ready patch up the systemctl stuff is because making it work from the systemctl variation also requires rectifying incomplete dependencies as the current systemctl file points back at /usr/share/varnish/reload-vcl which in turn points at /etc/default/varnish (the ostensibly deleted file if using systemctl).

**Comment by bzed** [comment]
If the systemd service would just use the defauls file instead of setting its own daemon options, things would be better.

**Comment by tfheen** [comment]
No,  `/etc/defaults/` files are a terrible idea and are really deprecated in a systemd world. They only existed in the first place because dpkg's conffile handling is less than great.

**Comment by bzed** [comment]
But right now things are completely broken. The reload script used by systemd reads the default file, which is also read by the init script. The systemd service uses its own stuff, which is ignored for a reload. Getting rid of the init script and the defaults file is totally awesome, but the current way is completely messed up. The only useful way for an upgrade - imho - would be to migrate the defaults file into a service file in /etc/systemd. Or - until things are fixed - use the defaults stuff in systemd.

**Comment by Dridi** [comment]
@bzed, lots of us agree that the current situation is far from ideal and I personally haven't changed my mind regarding the reload scripts. Changing start/reload mechanics would however break the upgrade path, or at the very least require more than a package update.

**Comment by Dridi** [comment]
Closing in favor of #70.
