### ISSUE TITLE
Remove -T and -S argument from default command line

### ISSUE THREAD

**Issue by gquintard** [varnishcache/pkg-varnish-cache#81]
-S and -T respectively specify the secret key and the admin socket to contact varnish, it's used notably by varnishadm and varnish-agent.

If no secret is given, varnish will generate one and if -T isn't specified, "localhost:0" is used. Local programs wishing to connect discover them through the vsm (-n param).

In my experience, virtually nobody connects to the socket from an external machine, but people do confuse the -T argument for the PROXY socket, change it and stuff breaks. So I'd like to remove cruft and remove the secret generation from packaging, and remove the -S/-T args from the command lines.

ping: @ssm, @ingvarha, @denisbr, @Dridi

**Comment by denisbr** [comment]
I'm all for this for the next major release, but I'm hesitant to change for the older series of packages.

**Comment by gquintard** [comment]
definitely targeting 6.0 here

**Comment by Dridi** [comment]
I agree with both proposals, less packaging work for us since `varnishd` already does the heavy lifting by default. In both cases it means that by default `varnishadm` could only be used by a local privileged user, which is already the case with today's packaging in order to access the VSM when varnish is started as a service (even the `-T` we currently ship only binds the loopback). For `-S` it means one less reason to fail the transaction at install time.

Now if `varnishd` starts binding random ports for the CLI socket, we need to make sure it won't be denied by selinux. I would even go one step further and not set `-a` by default, because if you use Varnish you will likely want it to listen to the HTTP port (`-a` is `:80` by default) and I wouldn't mind conflicting with other web servers on this port by default. If you co-locate Varnish and the backend, you will likely need to tweak ports anyway...

My only concern is where and how to document such a change.

**Comment by gquintard** [comment]
I actually don't agree about -a, for two reasons:
- it changes the default behavior
- people often change the port (to 80, true, but not necessarily), and to have it in the command line clearly shows where and how you can change it.

That being said, I wouldn't mind having ``-a :80 -a 127.0.0.1:8443,PROXY`` in the command line, with the hitch package defaulting to ``127.0.0.1:8443`` as backend, but that's a discussion for another ticket.

@dridi, do we even need to document the -S/-T removal for 6.0?

**Comment by Dridi** [comment]
> I actually don't agree about -a, for two reasons:
>
> * it changes the default behavior

Much like not relying on a secret file and binding random ports changes the current default behavior.

> * people often change the port (to 80, true, but not necessarily), and to have it in the command line clearly shows where and how you can change it.

My point is rather that Varnish is an HTTP server and should listen by default to the HTTP port. A major release is a good occasion to introduce a breaking change. Even in the redhat/fedora selinux policy `varnishd` is already labeled as an HTTP daemon and can listen to TCP 80 out of the box.

> That being said, I wouldn't mind having -a :80 -a 127.0.0.1:8443,PROXY in the command line, with the hitch package defaulting to 127.0.0.1:8443 as backend, but that's a discussion for another ticket.

On IRC we were also discussing the removal of `varnish.params` and I thought you'd mention it here too when you said you'd open a ticket. I guess this is a discussion for another ticket too.

> @Dridi, do we even need to document the -S/-T removal for 6.0?

Yes, according to our docs those packages are official, so I would expect to document breaking changes somewhere.

It could be in the future "Official packages for 6" section:

https://www.varnish-cache.org/releases/install_redhat.html
https://www.varnish-cache.org/releases/install_debian.html

**Comment by gquintard** [comment]
> Much like not relying on a secret file and binding random ports changes the current default behavior.
You know what I mean :-) The huge majority of the user won't see the -S/-T change.

I'll prepare a PR.

**Comment by gquintard** [comment]
@Dridi wouldn't we bee content with simply announcing the change in the packages changelogs?

**Comment by Dridi** [comment]
I think we should have this in the Varnish changelog, that's where people look for upgrade information. I guess we really should have a "changes in official packages" section.

And then we let downstream distributors decide whether they follow those changes. At least in Fedora I'm a aware of the formal Change process and I assume others do things similarly.

**Comment by ingvarha** [comment]
While most users just use varnishadm, as late as yesterday, I was asked on IRC about helping with a magento plugin that uses the varnish "telnet" admin interface.

Do you plan to completely remove the options, or just stop using them in a standard installation.

**Comment by gquintard** [comment]
@ingvarha we are just talking about the packaging, varnishd will still have the -S/-T options.

I didn't know about the magento plugin, that's quite ugly.

**Comment by Dridi** [comment]
> I didn't know about the magento plugin, that's quite ugly.

Well, that's the point of `-T`, allowing remote operations. And IMO such a plugin is one more reason to go ahead with this change because if you want to use the CLI remotely you need to figure a way to share the secret. Since we are discussing local-only operations by default with the packages, then we don't need a shared secret, only enough local privileges.

**Comment by Dridi** [comment]
Unless I see a compelling argument against, I'll vouch for @gquintard committing this change directly (you can still open a pull request if you want a review).

I didn't look closely but we need to clarify this first:

> I'm all for this for the next major release, but I'm hesitant to change for the older series of packages, as it will change behaviour, and likely affect someone out there.

@denisbr, do we have means to make this a 6.0-specific case? Or do we need to branch off current master for older releases? Or maybe we could have tags for older series (eg. `pkg-varnish-cache-4.1`) and only branch if we later need changes to the older releases.

Thoughts?

**Comment by denisbr** [comment]
This sounds good for the 6.0 release and future releases, but we should keep the old way for the older packages imo.

**Comment by Dridi** [comment]
I don't disagree. Closing this one in favor of #84.
