### ISSUE TITLE
Incompatible VMOD - hashes do not match

### ISSUE THREAD

**Issue by paulborile** [varnishcache/pkg-varnish-cache#91]
Hi, 
we release a varnish module in binary form and we do make them for almost all varnish versions in order to not have ABI mismatch problems. Our procedure builds the module .so by compiling it against the released versions that we download from git with `git checkout <release_hash>`. Release hashes are found at the releases link in github (https://github.com/varnishcache/varnish-cache/releases) and this as always worked fine (only one strange hash in 5.0 time ago) up to 5.2.0. We get this message while loading our binary module, built with 5.2.0 sources, commit 4c4875c , against 5.2.0 binary version we download from : https://packagecloud.io/varnishcache/varnish5/packages/ubuntu/xenial/varnish_5.2.0-1~xenial_amd64.deb/download.deb

```
Incompatible VMOD wurfl
	File name: /usr/lib64/varnish/vmods/libvmod_wurfl.so
	ABI mismatch, expected <Varnish 5.2.0 4c4875cbf>, got <Varnish 5.2.0 4c4875c>
```

Looks like the git hash short SHA is long 9 characters instead of 7 you used so far. Is this correct ?

**Comment by Dridi** [comment]
It looks like it depends on your git version :(

I noticed that short hashes were longer when I upgraded git to 2.13 but didn't pay attention to it.

What you should do instead is to install the `varnish-dev` package from packagecloud to make sure to build against the same ABI anyway. Technically, this is "working" because you build against sources but run against packages, different targets... But of course we don't want to consider them different if it's the same commit.

In `generate.py` we should probably replace `git show -s --pretty=format:%h` with `git rev-parse --short=7` to get a consistent short hash. And we should probably add a check to the release process from now on. To me, this is a problem in varnish-cache, not the packaging.

**Comment by paulborile** [comment]
Thanks, I'll repost in the correct repo
